### ISSUE TITLE
Add PWM module

### ISSUE THREAD

**Issue by PonomarevDA** [Innopolis-UAV-Team/lights_node#4]
Create a module besides lights and circuit status that subscribes to either RawCommand and ArrayCommand and set the specific PWM value.

The module itself should have the following parameters:
- pwm.cmd_ttl_ms: [0, 10000] means [TTL](https://en.wikipedia.org/wiki/Time_to_live). 0 value means disabled. Default is 500 ms.
- pwm.frequency: Pwm frequency from 50 to 400 Hz

The module should have a single group (later this number can be increased) of the parameters:
- pwm.*_sub: 0 means RawCommand, 1 means ArrayCommand, 2 is reserved for hardpoint.Command. Can be extended in future 
- pwm.*_ch: Index of setpoint channel. [-1; 255]. -1 means disabled
- pwm.*_min: PWM duration when setpoint is min.
- pwm.*_max: PWM duration when setpoint is max.
- pwm.*_def: PWM duration when setpoint is negative or there is no setpoint at all.

Check [this docs](https://docs.raccoonlab.co/guide/can_pwm/can_pwm_dronecan.html#_5-1-dronecan-interface) as an example of the interface.

**Comment by AsiiaPine** [comment]
Pull request created (#8 )

**Comment by PonomarevDA** [comment]
Done
